# Generated by Django 6.0.8 on 2026-08-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
