# Generated by Django 6.0.8 on 2026-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_tasks', '0003_task_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
