# Generated by Django 6.0.8 on 2026-08-22 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_current_owner(apps, schema_editor):
    """Existing rows predate the current_owner/created_by split -- give every
    project a sensible current owner (its historical creator) in one bulk
    query rather than a per-row Python loop."""
    Project = apps.get_model('projects_and_tasks', 'Project')
    Project.objects.filter(current_owner__isnull=True, created_by__isnull=False).update(
        current_owner=models.F('created_by'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_tasks', '0004_project_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_current_owner, migrations.RunPython.noop),
    ]
