# Generated by Django 6.0.8 on 2026-08-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_tasks', '0005_project_current_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='default_task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_task_types', to='projects_and_tasks.defaulttasktype'),
        ),
    ]
