# Generated by Django 6.0.8 on 2026-09-03 11:16

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_spent_time(apps, schema_editor):
    """Task.spent_time was a single overwritable field with no history or
    attribution -- see TaskTimeLog. Rather than silently losing whatever was
    already logged, give each task with a non-zero legacy value one
    TaskTimeLog entry standing in for that history, attributed to the
    assignee (or the creator, if unassigned)."""
    Task = apps.get_model('projects_and_tasks', 'Task')
    TaskTimeLog = apps.get_model('projects_and_tasks', 'TaskTimeLog')
    for task in Task.objects.exclude(spent_time__isnull=True).exclude(spent_time=datetime.timedelta(0)):
        attributed_to = task.assigned_to_id or task.created_by_id
        TaskTimeLog.objects.create(
            task=task, user_id=attributed_to, duration=task.spent_time,
            work_date=task.updated_at.date(), description='Migrated from legacy time tracking',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_tasks', '0006_default_config_traceability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('work_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='projects_and_tasks.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(backfill_legacy_spent_time, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='task',
            name='spent_time',
        ),
    ]
