# Generated by Django 6.0.8 on 2026-09-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_tasks', '0011_backfill_project_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapproval',
            name='late_by',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskapproval',
            name='submitted_late',
            field=models.BooleanField(default=False),
        ),
    ]
