# Generated by Django 6.0.8 on 2026-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_tasks', '0014_migrate_visibility_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('voided', 'Voided')], default='pending', max_length=10),
        ),
    ]
