# Generated by Django 6.0.8 on 2026-09-08 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_tasks', '0016_remove_approvalrequest_one_pending_approval_request_per_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('blocks', 'Blocks'), ('relates_to', 'Relates to')], default='blocks', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dependencies', to=settings.AUTH_USER_MODEL)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='projects_and_tasks.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects_and_tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['successor', 'kind'], name='projects_an_success_30b96c_idx'), models.Index(fields=['predecessor', 'kind'], name='projects_an_predece_e66de6_idx')],
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor', 'kind'), name='one_dependency_per_pair_and_kind'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='no_self_dependency')],
            },
        ),
    ]
