# Generated by Django 6.0.8 on 2026-09-09 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_allow_public_projects'),
        ('projects_and_tasks', '0017_taskdependency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalrequest',
            name='one_pending_approval_request_per_target',
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='kind',
            field=models.CharField(choices=[('project_visibility', 'Project visibility change'), ('task_proposal', 'Task proposal'), ('workload_override', 'Assignment over a workload limit')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('project_visibility', 'workload_override')), ('status', 'pending')), fields=('kind', 'target_type', 'target_id'), name='one_pending_approval_request_per_target'),
        ),
    ]
