# Generated by Django 6.0.8 on 2026-09-09 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_and_teams', '0003_default_config_traceability'),
        ('projects_and_tasks', '0018_remove_approvalrequest_one_pending_approval_request_per_target_and_more'),
        ('workforce', '0002_backfill_professions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.TextField(blank=True, default='')),
                ('background', models.TextField(blank=True, default='')),
                ('scope_in', models.TextField(blank=True, default='')),
                ('scope_out', models.TextField(blank=True, default='')),
                ('expected_outcome', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='projects_and_tasks.project')),
                ('required_departments', models.ManyToManyField(blank=True, related_name='required_by_briefs', to='departments_and_teams.department')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_by_briefs', to='workforce.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
