# Generated by Django 6.0.8 on 2026-09-09 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_company_allow_public_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('members', 'Members'), ('active_projects', 'Active projects'), ('departments', 'Departments'), ('teams', 'Teams'), ('storage_bytes', 'Storage bytes'), ('info_portal_pages', 'Info Portal pages'), ('integrations', 'Integrations'), ('ai_credits', 'AI credits'), ('ai_planning_generations', 'AI planning generations')], max_length=40)),
                ('period', models.CharField(blank=True, default='', max_length=7)),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='company.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'metric', 'period'], name='entitlement_company_8b5ded_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'metric', 'period'), name='one_usage_counter_per_company_metric_period')],
            },
        ),
    ]
