# Generated by Django 6.0.8 on 2026-09-08 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_company_allow_public_projects'),
        ('pages', '0002_folder_share'),
        ('projects_and_tasks', '0017_taskdependency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('project', 'Project'), ('company', 'Company'), ('folder', 'Info Portal folder')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_attachment_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.company')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pages.pagefolder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_documents', to='projects_and_tasks.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_documents', to='projects_and_tasks.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_shared', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'is_deleted'], name='documents_d_company_d9a729_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='documents_d_is_dele_8c5178_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['scope', 'project'], name='documents_d_scope_4ee43c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['scope', 'owner'], name='documents_d_scope_efcd81_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('folder__isnull', True), ('owner__isnull', False), ('project__isnull', True), ('scope', 'personal')), models.Q(('folder__isnull', True), ('owner__isnull', True), ('project__isnull', False), ('scope', 'project')), models.Q(('folder__isnull', True), ('owner__isnull', True), ('project__isnull', True), ('scope', 'company')), models.Q(('folder__isnull', False), ('owner__isnull', True), ('project__isnull', True), ('scope', 'folder')), _connector='OR'), name='document_scope_matches_its_owner'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['user', 'document'], name='documents_d_user_id_6410f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentshare',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='one_document_share_per_user'),
        ),
    ]
