# Generated by Django 6.0.8 on 2026-09-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_public_projects',
            field=models.BooleanField(default=False),
        ),
    ]
