# Generated by Django 6.0.8 on 2026-08-22 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('notifications_and_activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('project_created', 'Project Created'), ('project_completed', 'Project Completed'), ('project_ownership_transferred', 'Ownership Transferred'), ('member_invited', 'Member Invited'), ('member_joined', 'Member Joined'), ('member_removed', 'Member Removed'), ('department_created', 'Department Created'), ('team_created', 'Team Created')], max_length=40)),
                ('summary', models.CharField(max_length=255)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'company activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
