# Generated by Django 6.0.8 on 2026-08-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_and_activity', '0002_company_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('critical', 'Critical'), ('optional', 'Optional')], default='optional', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
