# Generated by Django 6.0.8 on 2026-08-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_and_activity', '0003_email_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('invitation_accepted', 'Invitation Accepted'), ('ai_generation_completed', 'AI Generation Completed'), ('ai_generation_failed', 'AI Generation Failed'), ('task_submitted_for_approval', 'Task Submitted For Approval'), ('task_approved', 'Task Approved'), ('task_rejected', 'Task Rejected'), ('deadline_extended', 'Deadline Extended'), ('project_auto_completed', 'Project Auto-Completed')], max_length=30),
        ),
    ]
