# Generated by Django 6.0.8 on 2026-08-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_and_activity', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('invitation_accepted', 'Invitation Accepted'), ('ai_generation_completed', 'AI Generation Completed'), ('ai_generation_failed', 'AI Generation Failed'), ('task_submitted_for_approval', 'Task Submitted For Approval'), ('task_approved', 'Task Approved'), ('task_rejected', 'Task Rejected'), ('deadline_extended', 'Deadline Extended'), ('project_auto_completed', 'Project Auto-Completed'), ('visibility_requested', 'Visibility Request'), ('visibility_approved', 'Visibility Request Approved'), ('visibility_denied', 'Visibility Request Denied')], max_length=30),
        ),
    ]
