# Generated by Django 6.0.8 on 2026-09-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_and_activity', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('invitation_accepted', 'Invitation Accepted'), ('ai_generation_completed', 'AI Generation Completed'), ('ai_generation_failed', 'AI Generation Failed'), ('task_submitted_for_approval', 'Task Submitted For Approval'), ('task_approved', 'Task Approved'), ('task_rejected', 'Task Rejected'), ('deadline_extended', 'Deadline Extended'), ('project_auto_completed', 'Project Auto-Completed'), ('visibility_requested', 'Visibility Request'), ('visibility_approved', 'Visibility Request Approved'), ('visibility_denied', 'Visibility Request Denied'), ('project_completed', 'Project Completed'), ('project_reopened', 'Project Reopened'), ('project_ownership_transferred', 'Project Ownership Transferred'), ('folder_shared', 'Folder Shared'), ('todos_generated', 'Todos Generated'), ('todos_generation_failed', 'Todos Generation Failed')], max_length=30),
        ),
    ]
