# Generated by Django 6.0.8 on 2026-09-09 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_allow_public_projects'),
        ('departments_and_teams', '0003_default_config_traceability'),
        ('event_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('no_response', 'No response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='no_response', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('personal', 'Personal'), ('custom', 'Custom'), ('team', 'Team'), ('department', 'Department'), ('company', 'Company')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['company', 'audience', 'start_at'], name='event_manag_company_19bbd4_idx'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_records', to='event_management.event'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['user', 'event'], name='event_manag_user_id_0d395f_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattendee',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='one_attendee_row_per_event_user'),
        ),
    ]
