# Generated by Django 6.0.8 on 2026-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ai_credit_pool_basis',
            field=models.CharField(choices=[('flat', 'Flat per company'), ('per_user', 'Per user')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_credits_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_model_tier',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('premium', 'Premium')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_planning_generations_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='info_portal_page_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='key',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('team', 'Team'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_active_projects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_departments_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_integrations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_teams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
