"""Opaque one-time tokens (invites, resets, etc.).

Only the hash is ever persisted -- a database dump must not hand out usable
tokens. SHA-256 (not a password hasher) is correct here because the input is
already high-entropy random data generated by us, not a user-chosen secret
that needs slow, salted hashing to resist guessing.
"""

import hashlib

from django.utils.crypto import get_random_string


def generate_token(length: int = 40) -> str:
    return get_random_string(length)


def hash_token(raw_token: str) -> str:
    return hashlib.sha256(raw_token.encode()).hexdigest()
