# Generated by Django 6.0.8 on 2026-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='past_due_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
