# Generated by Django 6.0.8 on 2026-09-09 15:16

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_company_allow_public_projects'),
        ('users', '0009_companyuserprofile_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('max_active_tasks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_utilisation_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('enforcement', models.CharField(choices=[('warn', 'Warn'), ('block', 'Block')], default='warn', max_length=10)),
                ('override_roles', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_policy', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultProfession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_professions', to='company.sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DefaultSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_skills', to='company.sector')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='company.company')),
                ('default_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_skills', to='workforce.defaultskill')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('learning', 'Learning'), ('working', 'Working knowledge'), ('strong', 'Strong'), ('expert', 'Expert')], default='working', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_skills', to='users.companyuserprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_skills', to='workforce.skill')),
            ],
            options={
                'ordering': ['skill__category', 'skill__name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='company.company')),
                ('default_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_professions', to='workforce.defaultprofession')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('name'), name='one_profession_per_company_name')],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['company', 'category'], name='workforce_s_company_c08bd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('name'), name='one_skill_per_company_name'),
        ),
        migrations.AddIndex(
            model_name='memberskill',
            index=models.Index(fields=['skill', 'level'], name='workforce_m_skill_i_c6419a_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberskill',
            constraint=models.UniqueConstraint(fields=('profile', 'skill'), name='one_level_per_profile_skill'),
        ),
    ]
