# Generated by Django 6.0.8 on 2026-08-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_and_teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='default_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_departments', to='departments_and_teams.defaultdepartment'),
        ),
    ]
