"""
Base Django settings for crm_backend project -- shared by both the
development and production settings modules (see __init__.py in this
package for how one gets selected). This is a structural split of what used
to be a single settings.py file (IMPLEMENTATION_PLAN.md Phase 0's
"establish production settings separation"); for any given DEBUG value, the
computed settings are unchanged from before the split -- every env(...) read
below is verbatim from the original file.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
import environ
from celery.schedules import crontab

# Initialize environ
env = environ.Env(
    # Set casting and default values
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1', '0.0.0.0']),
    CORS_ALLOWED_ORIGINS=(list, ['http://localhost:3000', 'http://127.0.0.1:3000', 'http://localhost:5173', 'http://127.0.0.1:5173']),
    CSRF_TRUSTED_ORIGINS=(list, ['http://localhost:3000', 'http://127.0.0.1:3000', 'http://localhost:5173', 'http://127.0.0.1:5173']),
)

# Read .env file


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Three .parent calls: this file lives at <project_root>/crm_backend/settings/base.py,
# so .parent -> settings/, .parent.parent -> crm_backend/, .parent.parent.parent
# -> <project_root>/ (where manage.py lives) -- one level deeper than when this
# was a flat crm_backend/settings.py file, since it's now inside a settings/ package.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

env.read_env(BASE_DIR.parent/'.env')
SECRET_KEY = env('SECRET_KEY')


DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
        # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # local apps
    'company',
    'users',
    'permissions',
    'subscriptions',
    'plans',
    'departments_and_teams',
    'projects_and_tasks',
    'event_management',
    'notifications_and_activity',
    'analytics',
    'messaging',
    'ai_agent',
    'connected_apps',
    'pages',
    'todos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'utils.middleware.RequestIDMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(env('DATABASE_URL'))
}
# Async Django views should not retain persistent connections. Let the database
# driver/pool manage connections instead.
DATABASES['default']['CONN_MAX_AGE'] = 0


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# WhiteNoise serves collected static files (mainly /admin/) directly from
# the ASGI app -- uvicorn/gunicorn don't auto-serve static/ the way
# `runserver` does in DEBUG. Media (user uploads) is unaffected; it stays on
# local disk for V1 and isn't served through this.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Defense-in-depth above projects_and_tasks.services.MAX_DOCUMENT_SIZE_BYTES
# (10MB): make sure Django's own request-parsing layer doesn't reject a
# legitimate upload before the app-level content-type/size check even runs.
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=50),
    # 'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# CORS settings
CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')

# Used to build invite-accept and Stripe Checkout success/cancel links
# (api/api.py, users/tasks.py, users/services.py). Was previously read via
# getattr(settings, 'FRONTEND_URL', ...) with no assignment here, so it was
# silently always the hardcoded fallback regardless of .env -- fixed.
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')

# Stripe settings
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET')

# Celery / Redis. Transport only -- Django owns all authoritative state
# (DEVELOPMENT_RULES Rule 5); a task can run twice, so task bodies must stay
# idempotent (Rule 8).
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=False)
CELERY_TASK_EAGER_PROPAGATES = True

# Two queues (Phase 11): 'heavy' for slow/external-call work (AI generation),
# 'simple' for everything else. Keeps a slow LLM call from starving quick
# jobs like invite email delivery, and vice versa -- each gets its own
# worker process in docker-compose.yml.
CELERY_TASK_DEFAULT_QUEUE = 'simple'
CELERY_TASK_ROUTES = {
    'ai_agent.tasks.process_ai_generation': {'queue': 'heavy'},
    'ai_agent.tasks_assistant.process_assistant_query': {'queue': 'heavy'},
    'ai_agent.tasks_health.process_health_summary': {'queue': 'heavy'},
}
CELERY_BEAT_SCHEDULE = {
    'retry-pending-invite-emails': {
        'task': 'users.tasks.retry_pending_invite_emails_task',
        'schedule': crontab(minute='*/15'),
    },
}

# utils/rate_limit.py guard on signup/signin/invite endpoints. Off by
# default in tests (conftest.py) so the suite never needs a real Redis.
RATE_LIMIT_ENABLED = env.bool('RATE_LIMIT_ENABLED', default=True)

# FastAPI AI service (Phase 6/7). Django never calls this synchronously from
# a request -- only the Celery worker does (ai_agent/tasks.py).
WORKROOM_AI_SERVICE_URL = env('WORKROOM_AI_SERVICE_URL', default='http://localhost:8001')
WORKROOM_AI_SERVICE_TOKEN = env('WORKROOM_AI_SERVICE_TOKEN', default='')
WORKROOM_AI_SERVICE_TIMEOUT = env.float('WORKROOM_AI_SERVICE_TIMEOUT', default=90.0)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = env('COMPANY_EMAIL')
EMAIL_HOST_PASSWORD = env('EMAIL_PASSWORD')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = True

# Structured logging (Phase 11). request_id comes from utils/middleware.py
# via utils/logging.py's filter; '-' outside a request (e.g. management
# commands) or inside a Celery task (which uses its own correlation keys).
LOG_LEVEL = env('LOG_LEVEL', default='INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {'()': 'utils.logging.RequestIDFilter'},
    },
    'formatters': {
        'structured': {
            'format': '%(asctime)s level=%(levelname)s logger=%(name)s request_id=%(request_id)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'structured',
            'filters': ['request_id'],
        },
    },
    'root': {'handlers': ['console'], 'level': LOG_LEVEL},
    'loggers': {
        'django': {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
        'celery': {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
    },
}
