# Generated by Django 6.0.8 on 2026-08-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuserprofile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('CM', 'Company Manager'), ('DL', 'Department Leader'), ('DM', 'Department Member')], default='Owner', max_length=200),
        ),
        migrations.AlterField(
            model_name='pendinginvite',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('CM', 'Company Manager'), ('DL', 'Department Leader'), ('DM', 'Department Member')], default='Owner', max_length=200),
        ),
    ]
