# Generated by Django 6.0.8 on 2026-08-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_companyuserprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
