# Generated by Django 6.0.8 on 2026-08-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_companyuserprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
