# Generated by Django 6.0.8 on 2026-08-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyuserprofile',
            name='skype',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
