# Generated by Django 6.0.8 on 2026-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_backfill_owner_company_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
