# Generated by Django 6.0.8 on 2026-09-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_companyuserprofile_availability'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserprofile',
            name='profession_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='workforce.profession'),
        ),
        migrations.AddField(
            model_name='companyuserprofile',
            name='weekly_capacity_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
