# Generated by Django 6.0.8 on 2026-09-09 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_company_allow_public_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('source_control', 'Source control'), ('storage', 'File storage'), ('calendar', 'Calendar'), ('chat', 'Chat')], max_length=30)),
                ('available_scopes', models.JSONField(blank=True, default=list)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='company.company')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_integrations', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='integrations.integrationprovider')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_access_token', models.TextField(blank=True, default='')),
                ('encrypted_refresh_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='integrations.integration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(max_length=255)),
                ('external_username', models.CharField(blank=True, default='', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_links', to='integrations.integrationprovider')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='integrations.integration')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.integrationprovider')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalObjectLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.UUIDField()),
                ('external_type', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('external_state', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='company.company')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_object_links', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='integrations.integration')),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='integration_target__f386c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('integration', 'target_type', 'target_id', 'external_type', 'external_id'), name='one_external_link_per_pair')],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['company', 'is_active'], name='integration_company_3138bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(fields=('company', 'provider'), name='one_integration_per_company_provider'),
        ),
        migrations.AddConstraint(
            model_name='externalidentitylink',
            constraint=models.UniqueConstraint(fields=('company', 'user', 'provider'), name='one_identity_link_per_company_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='externalidentitylink',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'external_user_id'), name='one_workroom_user_per_external_account'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'received_at'], name='integration_status_7b7642_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'external_event_id'), name='one_webhook_event_per_provider_event_id'),
        ),
    ]
