# Generated by Django 6.0.8 on 2026-09-07 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('project.ownership_transferred', 'Project ownership transferred'), ('project.deadline_changed', 'Project deadline changed'), ('project.visibility_changed', 'Project visibility changed'), ('task.deadline_changed', 'Task deadline changed'), ('task.approved', 'Task approved'), ('task.approval_rejected', 'Task approval rejected'), ('member.role_changed', 'Member role changed'), ('member.deactivated', 'Member deactivated'), ('member.reactivated', 'Member reactivated'), ('member.removed', 'Member removed')], max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.UUIDField()),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='audit_audit_company_e8544b_idx'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_audit_target__19f19a_idx'), models.Index(fields=['company', 'action', '-created_at'], name='audit_audit_company_bd2790_idx')],
            },
        ),
    ]
