# Generated by Django 6.0.8 on 2026-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('project.ownership_transferred', 'Project ownership transferred'), ('project.deadline_changed', 'Project deadline changed'), ('project.visibility_changed', 'Project visibility changed'), ('task.deadline_changed', 'Task deadline changed'), ('task.approved', 'Task approved'), ('task.approval_rejected', 'Task approval rejected'), ('member.role_changed', 'Member role changed'), ('member.deactivated', 'Member deactivated'), ('member.reactivated', 'Member reactivated'), ('member.removed', 'Member removed'), ('company.settings_changed', 'Company settings changed')], max_length=64),
        ),
    ]
