from django.db import models
from users.models import CompanyUserProfile
from utils.models import UUIDModel


class Permission(UUIDModel):
    """DB mirror of one permission code declared in the RBAC YAML catalog
    (permissions and roles/roles_permission.yaml). Never read on the
    authorization hot path -- see permissions.catalog -- this exists purely
    for auditability and a future admin UI. Regenerated by
    ``manage.py seed_permissions``; never hand-edited."""

    code = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ['code']

    def __str__(self):
        return self.code


class RolePermission(UUIDModel):
    """DB mirror of one role -> permission grant. ``role`` intentionally
    mirrors CompanyUserProfile.Role.choices rather than a separate Role
    table/model -- role is already an existing concept, not a new one."""

    role = models.CharField(max_length=20, choices=CompanyUserProfile.Role.choices)
    permission = models.ForeignKey(Permission, on_delete=models.CASCADE, related_name='role_grants')

    class Meta:
        unique_together = ('role', 'permission')
        ordering = ['role', 'permission__code']

    def __str__(self):
        return f'{self.role} -> {self.permission.code}'
