# Generated by Django 6.0.8 on 2026-08-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_agent', '0001_initial'),
        ('projects_and_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='projects_and_tasks.project'),
        ),
    ]
