# Generated by Django 6.0.8 on 2026-08-23 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0005_aigeneration_prompt_aigeneration_saved_at_and_more'),
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantquery',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='ai_assistant_queries', to='pages.page'),
        ),
        migrations.AddField(
            model_name='aigeneratedtask',
            name='suggested_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='max_tasks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='requested_assignee_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
