# Generated by Django 6.0.8 on 2026-08-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0006_aiassistantquery_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneration',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
