# Generated by Django 6.0.8 on 2026-09-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0008_aitodogeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantquery',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiassistantquery',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private to the person who asked'), ('project', 'Shared with the project')], default='private', max_length=20),
        ),
    ]
