# Generated by Django 6.0.8 on 2026-09-09 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0009_aiassistantquery_shared_at_and_more'),
        ('projects_and_tasks', '0018_remove_approvalrequest_one_pending_approval_request_per_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedtask',
            name='suggested_assignee_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aigeneratedtask',
            name='suggested_assignee_over_capacity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aigeneratedtask',
            name='suggested_assignee_rationale',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='assignee_refs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='fallback_from',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='aigeneration',
            index=models.Index(fields=['project', 'status'], name='ai_gen_project_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='aigeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('project', 'idempotency_key'), name='one_generation_per_project_idempotency_key'),
        ),
    ]
