# Generated by Django 6.0.8 on 2026-09-10 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0010_aigeneratedtask_suggested_assignee_accepted_and_more'),
        ('projects_and_tasks', '0019_projectbrief'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefAssist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('extracting', 'Extracting'), ('extracted', 'Extracted, awaiting confirmation'), ('interpreting', 'Interpreting'), ('interpreted', 'Interpreted, awaiting confirmation'), ('ready', 'Confirmed, ready to plan'), ('failed', 'Failed')], default='extracting', max_length=20)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_chars', models.PositiveIntegerField(default=0)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('interpretation', models.JSONField(blank=True, default=dict)),
                ('extraction_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('interpretation_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_assists', to='projects_and_tasks.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brief_assists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='ai_agent_br_project_4d99eb_idx')],
            },
        ),
    ]
